name: Hello World Workflow
on: push
jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
      - uses: ./action-puller
        with:
          MY_NAME: "Fred"
